# https://cloud.google.com/appengine/docs/standard/python3/runtime#python-3.8
runtime: python310
instance_class: F1

# entrypoint is not neccesary because search for main.py in root with object app 
# entrypoint: gunicorn -b:$PORT falken_teleworking.main:app (https://docs.gunicorn.org/en/stable/run.html)
entrypoint: gunicorn -b:$PORT 'falken_plants.app:create_app()'
# No incluyas gunicorn en requirements.txt, a menos que especifiques el entrypoint

env_variables:
  LEVEL_LOG: ["INFO, WARNING, ERROR"]
  CONFIG_MODE: "production" 

  
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

includes:
- credentials.yaml