# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /plants:
    get:
      operationId: "urls.list_create_plants"
      tags:
        - "Plants"
      summary: "Read the list of plants"
      responses:
        "200":
          description: "Successfully read plants list"
    post:
      operationId: "urls.list_create_plants"
      tags:
        - "Plants"
      summary: "Create a plant"
      responses:
        "200":
          description: "Successfully plant created"